// 
// Decompiled by Procyon v0.5.36
// 

package com.google.android.gms.internal;

import android.support.annotation.Nullable;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;
import android.support.annotation.NonNull;
import com.google.android.gms.common.internal.zzbo;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;

public final class zzbeh<R extends Result> extends PendingResult<R>
{
    private final Status mStatus;
    
    public zzbeh(final Status mStatus) {
        zzbo.zzb(mStatus, "Status must not be null");
        zzbo.zzb(!mStatus.isSuccess(), (Object)"Status must not be success");
        this.mStatus = mStatus;
    }
    
    @NonNull
    @Override
    public final R await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @NonNull
    @Override
    public final R await(final long n, @NonNull final TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @NonNull
    final Status getStatus() {
        return this.mStatus;
    }
    
    @Override
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void setResultCallback(@NonNull final ResultCallback<? super R> resultCallback) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void setResultCallback(@NonNull final ResultCallback<? super R> resultCallback, final long n, @NonNull final TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @NonNull
    @Override
    public final <S extends Result> TransformedResult<S> then(@NonNull final ResultTransform<? super R, ? extends S> resultTransform) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void zza(@NonNull final zza zza) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Nullable
    @Override
    public final Integer zzpo() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
